name: list

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - env:
          GOPROXY: "proxy.golang.org"
        run: go list -m github.com/cardinalby/go-lccore@${{ github.ref_name }}
